services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123455
      POSTGRES_DB: gartexhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:123123455@db:5432/gartexhub
      PORT: 4000
    ports:
      - "4000:4000"
      - "4173:4173"
      - "5173:5173"
    command: bash -lc "./scripts/run.sh --dev-or-preview=preview --localrunning-or-incloud=false --iwanttorunrunfrontendby=backend --port-backend=4000"

  opensearch:
    image: opensearchproject/opensearch:2.13.1
    environment:
      discovery.type: single-node
      "plugins.security.disabled": "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

volumes:
  postgres_data:
  opensearch_data:
