// Generated by scripts/generate-themes.py. Do not hand-edit.
export const DEFAULT_THEME = "blue";
export const THEMES = [
	{ slug: "blue", label: "Deep Sky Blue / Cyan Glass" },
	{ slug: "aurora", label: "Midnight Aurora" },
	{ slug: "violet", label: "Obsidian Violet" },
	{ slug: "sapphire", label: "Royal Sapphire" },
	{ slug: "arctic", label: "Arctic Ocean" },
	{ slug: "emerald", label: "Emerald Noir" },
	{ slug: "blurple", label: "Blurple Fusion" },
	{ slug: "mono", label: "Obsidian Mono" },
	{ slug: "plasma", label: "Cyberpunk Plasma" },
	{ slug: "solaris", label: "Solaris" },
	{ slug: "forest", label: "Forest Glass" },
	{ slug: "crimson", label: "Crimson Night" },
];
export const VALID_THEMES = new Set(THEMES.map((t) => t.slug));
