// Generated by scripts/generate-themes.py. Do not hand-edit.
export const THEME_CHARTS = {
	blue: ["#3B82F6", "#10B981", "#F59E0B", "#EF4444", "#8B5CF6", "#EC4899", "#06B6D4", "#84CC16"],
	aurora: ["#6366F1", "#22D3EE", "#10B981", "#F59E0B", "#F43F5E", "#3B82F6", "#A78BFA", "#84CC16"],
	violet: ["#8B5CF6", "#6366F1", "#22D3EE", "#10B981", "#F59E0B", "#F43F5E", "#3B82F6", "#EC4899"],
	sapphire: [
		"#2563EB",
		"#38BDF8",
		"#10B981",
		"#F59E0B",
		"#EF4444",
		"#1D4ED8",
		"#60A5FA",
		"#06B6D4",
	],
	arctic: ["#0891B2", "#22D3EE", "#14B8A6", "#F59E0B", "#EF4444", "#0EA5E9", "#67E8F9", "#84CC16"],
	emerald: ["#10B981", "#14B8A6", "#38BDF8", "#F59E0B", "#F43F5E", "#22C55E", "#6EE7B7", "#A3E635"],
	blurple: ["#5865F2", "#7C3AED", "#22D3EE", "#43B581", "#FEE75C", "#ED4245", "#818CF8", "#EB459E"],
	mono: ["#737373", "#60A5FA", "#059669", "#D97706", "#DC2626", "#A3A3A3", "#404040", "#38BDF8"],
	plasma: ["#FF2DAA", "#8B5CF6", "#22D3EE", "#00E69A", "#FFB020", "#FF2D55", "#3B82F6", "#FF6EC7"],
	solaris: ["#F97316", "#EC4899", "#8B5CF6", "#16A34A", "#F59E0B", "#E11D48", "#FDBA74", "#14B8A6"],
	forest: ["#16A34A", "#059669", "#14B8A6", "#B45309", "#DC2626", "#4ADE80", "#86EFAC", "#84CC16"],
	crimson: ["#E11D48", "#8B5CF6", "#F472B6", "#10B981", "#F59E0B", "#EF4444", "#FB7185", "#FBBF24"],
};
