-- HyperCache Phase 3 — migration DRAFT (do NOT apply directly).
-- Generated by hand; run `npx prisma migrate dev` on a machine with DB
-- access to produce the real migration. Review sequence ownership after apply.

-- 1) Syncable entities: version + content hash (backfill-safe defaults).
ALTER TABLE "requirements" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "requirements" ADD COLUMN IF NOT EXISTS "content_hash" TEXT;

ALTER TABLE "company_products" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "company_products" ADD COLUMN IF NOT EXISTS "content_hash" TEXT;

ALTER TABLE "feed_posts" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "feed_posts" ADD COLUMN IF NOT EXISTS "content_hash" TEXT;

-- 2) Append-only change ledger.
CREATE TABLE IF NOT EXISTS "sync_changes" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "seq" BIGSERIAL NOT NULL UNIQUE,
  "scope" TEXT,
  "entity_type" TEXT NOT NULL,
  "entity_id" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "entity_version" INTEGER NOT NULL,
  "content_hash" TEXT,
  "occurred_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "sync_changes_operation_check"
    CHECK ("operation" IN ('CREATE', 'UPDATE', 'DELETE'))
);

CREATE INDEX IF NOT EXISTS "sync_changes_seq_idx" ON "sync_changes" ("seq");
CREATE INDEX IF NOT EXISTS "sync_changes_entity_type_entity_id_idx"
  ON "sync_changes" ("entity_type", "entity_id");
